STITCH-1398: Add support for BsonType
10gen/gojsonschema pull request #1
Opened 2018-04-23 06:58 UTC by haleyowen

2018-04-23 20:22 UTC, mpobrien requested changes
Looks good so far. We're gonna need to also update the library so that it can accept a `bson.D` as an "object" (and ensure that it doesn't get accepted as an "array", even though bson.D is an array type in go).

It might be good to also examine the server's test suites to get an idea for any other things we should cover that might be missing; take a look through https://github.com/mongodb/mongo/tree/master/jstests/core/json_schema

2018-04-23 20:22 UTC, mpobrien commented on jsonschema_test.go
> +				{
we've got a ton of these test cases and it takes up a lot of lines of code and is tougher to read.
Maybe we could just make some helper functions for this? I'm imagining something like:
```
func testCaseObjectID(inputName string, shouldMatch bool){ 
   tc := jsonSchemaTestCase{ 
         Data: bson.NewObjectId(),
         Description: fmt.Sprintf("a %s is an objectid", inputName),
         Valid: shouldMatch,
   } 
   if !shouldMatch{
       tc.Description = fmt.Sprintf("a %s is not an objectid", inputName)
   }
   return tc
}
```

Then throughout the test cases you can just do something like `testCaseObjectID("integer", false)`. Could also make it even more generic by just using constants, like `bsonTestCase(TESTVALUE_OBJECTID, "integer", false)`. This will also make it easier to add more types/tests over time.

2018-04-23 20:22 UTC, mpobrien commented on schema.go
> +					err = currentSchema.types.Add(TYPE_BOOLEAN)
further down in this function (L336 - L351) it looks like it also handles the case where the value for KEY_TYPE is a slice. In that code path, i think we would need to do the same logic here to allow that to also accept either "boolean" and "bool" if either one appears in the array.

2018-04-23 20:22 UTC, mpobrien commented on validation.go
> +				if !currentSubSchema.containsValidType(currentNode, result, context, TYPE_DECIMAL128) {
should this also be considered valid if the field specifies TYPE_NUMBER instead of TYPE_DECIMAL128?

2018-04-23 20:22 UTC, mpobrien commented on jsonschema_test.go
> +			Schema: map[string]interface{}{"bsonType": "decimal"},
can we add a couple tests that exercise some of the other basic jsonschema mechanics but using bsonTypes? There's things like `oneOf`, `anyOf`, etc. which should still be valid with `bsonType` nested inside.

2018-04-26 04:26 UTC, haleyowen commented on validation.go
> +				if !currentSubSchema.containsValidType(currentNode, result, context, TYPE_DECIMAL128) {
👍 i also added for ints and doubles too

2018-04-26 18:41 UTC, haleyowen commented
@mpobrien this is probably ready for another pass. i added more tests but maybe should add more. I'm not sure how crazy i should go with it.

2018-05-01 04:58 UTC, mburdette approved these changes
LGTM although, I wouldn't say i'm super familiar with this code as a whole

2018-05-01 12:19 UTC, mpobrien approved these changes
A note about testing for bson.D but otherwise LGTM.

2018-05-01 12:19 UTC, mpobrien commented on jsonschema_test.go
> +				bsonTestCase("both properties present and valid is valid", map[string]interface{}{"foo": 1, "bar": "baz"}, true),
for the tests in this block (L493-593) that use map[string]interface{}, we should also include the equivalent but using `bson.D`s as well.

2018-05-01 15:25 UTC, merged