REALMC-7586: Include new sync types (UUID, Mixed) and expose information to determine container types (Dictionary, Set)
10gen/gojsonschema pull request #18
Opened 2020-12-14 22:55 UTC by tkaye407

2020-12-14 22:56 UTC, tkaye407 commented on .gitignore
> +.idea/
This was annoying me, so I added it in here

2020-12-14 22:56 UTC, tkaye407 commented on schema.go
> +
gofmt fixed this

2020-12-14 22:57 UTC, tkaye407 commented on schemaPool.go
> +		if bsonD, isBsonD := cachedSpd.Document.(bson.D); isBsonD {
This fixes an issue where the tests were failing here: https://github.com/10gen/gojsonschema/blob/9b64c19c895bb7d38d2526ab22303b2bc8510f46/jsonschema_test.go#L1174

2020-12-14 22:58 UTC, tkaye407 commented on subSchema.go
> +func (s *SubSchemaAccessor) UniqueItems() bool {
This exposes what we need to determine if this is a Set / Dictionary

2020-12-15 20:01 UTC, joshmadewell requested changes

2020-12-15 20:01 UTC, joshmadewell commented on schemaPool.go
> +		if bsonD, isBsonD := cachedSpd.Document.(bson.D); isBsonD {
nit: it's more idiomatic to use `ok` here I think? shouldn't affect the `ok` on 196 either.

2020-12-15 20:01 UTC, joshmadewell commented on subSchema.go
> +func (s *SubSchemaAccessor) UniqueItems() bool {
it's totally fine if you don't want to do this but is there anyway I can get you to move all of `SubSchemaAccessor` out to it's own file? It should help reduce merge conflicts in the future when we try to update this file with upstream.

2020-12-15 20:01 UTC, joshmadewell commented on subSchema.go
> +func (s *SubSchemaAccessor) AdditionalProperties() []string {
This accessor doesn't make much sense to me. `additionalProperties` can only be a `boolean` or an `object` but we're returning that it's a `[]string`. This looks like business logic more than something I'd expect to be in the library.

2020-12-15 20:01 UTC, joshmadewell commented on subSchema.go
> +func (s *SubSchemaAccessor) AdditionalProperties() []string {
https://json-schema.org/understanding-json-schema/reference/object.html#id2

2020-12-16 14:38 UTC, tkaye407 commented on subSchema.go
> +func (s *SubSchemaAccessor) AdditionalProperties() []string {
Changed this to return (bool, SubSchemaAccessor)

2020-12-20 21:57 UTC, tkaye407 commented
@joshmadewell I see you are working tomorrow but then heading out for a bit, let me know if you have time to take another look at this before heading out as it blocks the rest of the DataType support work

2020-12-21 09:52 UTC, joshmadewell approved these changes
got one more comment re: `ok` vs `isBlegh` but otherwise seems good. would like to see one person from sync review this before we merge just to 👍 that we're implementing the expected spec but nothing egregious here imo

2020-12-21 09:52 UTC, joshmadewell commented on schemaPool.go
> +		if subDoc, isSubDoc := entry.Value.(bson.D); isSubDoc {
nit: using `ok` throughout this function in these type assertions -- the reason for `ok` can be implied by the code itself, the variable name seems unnecessary :D

2020-12-21 15:47 UTC, mpobrien approved these changes

2020-12-21 16:18 UTC, merged