STITCH-1423: Add JSON schema support for validate
10gen/gojsonschema pull request #2
Opened 2018-05-15 20:42 UTC by haleyowen

2018-05-16 23:11 UTC, mpobrien requested changes
Looks good! I think the one main change we need is around error handling, but this feels like the right approach. I'll do another pass tonight to look a little more closely at the test cases since you mentioned that you were concerned about that part in particular.

2018-05-16 23:11 UTC, mpobrien commented on expression_evaluator.go
> +	Evaluate(expression interface{}, fieldPath []string) bool
I think this should return an `error`. If it returns `nil` then that will just mean "valid". If it's not nil, we should be able to propagate the error message out to the caller. This would allow us to log more information about why something was flagged as not valid in cases where one of these evaluations was the root cause.

2018-05-16 23:11 UTC, mpobrien commented on expression_evaluator.go
> +type ValidateEvaluator struct {}
naming nit: since this one always results in a "valid" outcome, i might call this one something like "NoopEvaluator" instead.

2018-05-16 23:11 UTC, mpobrien commented on jsonschema_test.go
> +				validateTestCase("does not pass when validate is false with bson.D", "haley", false, false, validateExpression, []string{}),
q: a couple of these test cases reference `bson.D` in their description, but i don't see where we actually use one?

2018-05-16 23:16 UTC, haleyowen commented on jsonschema_test.go
> +				validateTestCase("does not pass when validate is false with bson.D", "haley", false, false, validateExpression, []string{}),
oh shoot, i copy pasta'd some of this.

2018-05-17 20:04 UTC, mpobrien approved these changes
LGTM 👍

2018-05-18 16:59 UTC, haleyowen commented
@mburdette Are you still looking at this or is it okay for me to merge?

2018-05-18 17:03 UTC, mburdette approved these changes
LGTM nice work! sorry I thought I approved this last night!

2018-05-18 17:39 UTC, merged